# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 860)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 461, 71))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.label.setObjectName("label")
        self.have_complete_data_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.have_complete_data_checkBox.setGeometry(QtCore.QRect(610, 90, 291, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.have_complete_data_checkBox.setFont(font)
        self.have_complete_data_checkBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.have_complete_data_checkBox.setObjectName("have_complete_data_checkBox")
        self.data_list_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.data_list_tableWidget.setGeometry(QtCore.QRect(20, 190, 881, 231))
        self.data_list_tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);\n"
"background-color: rgb(255, 255, 127);")
        self.data_list_tableWidget.setObjectName("data_list_tableWidget")
        self.data_list_tableWidget.setColumnCount(0)
        self.data_list_tableWidget.setRowCount(0)
        self.have_been_merged_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.have_been_merged_checkBox.setGeometry(QtCore.QRect(610, 140, 291, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.have_been_merged_checkBox.setFont(font)
        self.have_been_merged_checkBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.have_been_merged_checkBox.setObjectName("have_been_merged_checkBox")
        self.start_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.start_pushButton.setGeometry(QtCore.QRect(360, 100, 201, 71))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(24)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.start_pushButton.setObjectName("start_pushButton")
        self.show_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.show_pushButton.setGeometry(QtCore.QRect(50, 100, 131, 71))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.show_pushButton.setFont(font)
        self.show_pushButton.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.show_pushButton.setObjectName("show_pushButton")
        self.merged_data_list_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.merged_data_list_tableWidget.setGeometry(QtCore.QRect(20, 440, 881, 311))
        self.merged_data_list_tableWidget.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.merged_data_list_tableWidget.setObjectName("merged_data_list_tableWidget")
        self.merged_data_list_tableWidget.setColumnCount(0)
        self.merged_data_list_tableWidget.setRowCount(0)
        self.display_combine_data_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.display_combine_data_pushButton.setGeometry(QtCore.QRect(680, 760, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.display_combine_data_pushButton.setFont(font)
        self.display_combine_data_pushButton.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"background-color: rgb(255, 0, 0);")
        self.display_combine_data_pushButton.setObjectName("display_combine_data_pushButton")
        self.now_show_patient_information_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.now_show_patient_information_ComboBox.setGeometry(QtCore.QRect(20, 760, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.now_show_patient_information_ComboBox.setFont(font)
        self.now_show_patient_information_ComboBox.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.now_show_patient_information_ComboBox.setObjectName("now_show_patient_information_ComboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "      Data Combiner"))
        self.have_complete_data_checkBox.setText(_translate("MainWindow", "Have complete data"))
        self.have_been_merged_checkBox.setText(_translate("MainWindow", "Have been merged"))
        self.start_pushButton.setText(_translate("MainWindow", "START"))
        self.show_pushButton.setText(_translate("MainWindow", "SHOW"))
        self.display_combine_data_pushButton.setText(_translate("MainWindow", "Display Combine data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
